chore: update protocol (#4879)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,3 +32,10 @@ jobs:
 
             - name: 📦 Build
               run: pnpm build:ci
+
+            - name: Check for uncommitted changes
+              run: |
+                  if [[ -n $(git status --porcelain) ]]; then
+                      echo "Error: Uncommitted changes detected after build."
+                      exit 1
+                  fi
